version: 0.2

phases:
  pre-build:
    commands:
      - VARIABLES=$(cat project-config)
      - export $VARIABLES
  build:
    on-failure: ABORT
    commands:
      - docker build --tag spacegame-test --target test .
      - docker run spacegame-test 
      - docker build --tag spacegame-$SG_MAJOR_VERSION.$SG_MINOR_VERSION.$SG_PATCH_VERSION:$(date +%s) --target release .
