version: 0.2

phases:
  build:
    on-failure: ABORT
    commands:
      - echo 'Building test image...'
      - docker build --tag spacegame-test --target test .
      - echo '\nRunning tests...'
      - docker run spacegame-test 
      - echo '\nBuilding release image...'
      - docker build --tag spacegame-0.1.0:${CODEBUILD_BUILD_ID} --target release .
